### ISSUE TITLE
Not found enroll_idmap.h5

### ISSUE THREAD

**Issue by chamecall** [Anwarvic/Speaker-Recognition#12]
I have downloaded your prepared features and then try to continue with the step N4 and run `ubm.py`.
In the process I've got the following error:

`INFO:root:Feature-Server is created
INFO:root:Training...
Iteration #1: 100%|███████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.51s/it]
Iteration #2: 100%|███████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:23<00:00, 11.74s/it]
Iteration #2: 100%|███████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:23<00:00, 11.88s/it]
Iteration #4: 100%|███████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:48<00:00, 12.08s/it]
Iteration #4: 100%|███████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:52<00:00, 13.18s/it]
Iteration #4: 100%|███████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:50<00:00, 12.64s/it]
INFO:root:Saving the model ubm_64.h5 at /home/algernone/Speaker-Recognition/outpath/ubm
Traceback (most recent call last):
  File "ubm.py", line 202, in <module>
    ubm.train()
  File "ubm.py", line 67, in train
    enroll_idmap = sidekit.IdMap.read(os.path.join(self.BASE_DIR, "task", "enroll_idmap.h5"))
  File "/home/algernone/Speaker-Recognition/sidekit/bosaris/idmap.py", line 281, in read
    with h5py.File(input_file_name, "r") as f:
  File "/home/algernone/anaconda3/envs/scienv/lib/python3.6/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/home/algernone/anaconda3/envs/scienv/lib/python3.6/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '/home/algernone/Speaker-Recognition/outpath/task/enroll_idmap.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
`

So to have the file (enroll_idmap.h5) have I to run all the steps or it can be achieved by another approach?

**Comment by ABexit** [comment]
I  got the same problem, do you have solved it?
