### ISSUE TITLE
how to train ivector?

### ISSUE THREAD

**Issue by yangxiaokang** [Anwarvic/Speaker-Recognition#2]
how to get plda_idmap.h5 and tv_idmap.h5?
thanks

**Comment by Anwarvic** [comment]
Hi @yangxiaokang, 

So sorry for responding almost a month later, but I was slammed at work.
yes, you are right... I didn't specify how to create them as I didn't know back then. But, now I have added the creation code in `data_init.py` script. Feel free to check it.

Also, I have updated the project description and make it easier to understand.

Also, I have updated `i-vector.py` script that you need to train an i-vector model. it still needs some more work, but it's working!

**Comment by Anwarvic** [comment]
I will close this issue but feel free to reopen it!!
